app/urls.py
from django.urls import path

from .views import (
    make_appointment, logout_page, login_page,
    appointmets, get_appointments_api,
)

app_name = 'app'


urlpatterns = [
    path('marcacoes/', appointmets, name='marcacoes'),
    path('marcar-consulta/', make_appointment,
         name='make_appointment'),

    # APIs
    path('get_appointments_api/', get_appointments_api),

    path('logout/', logout_page, name='logout'),
    path('login/', login_page,
		 name="login"),
]

proj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls',
                     namespace='app'))
]

app/forms.py
from django import forms
from django.utils import timezone

from ._helpers import PRIORITY


class MonthInput(forms.DateInput):
    input_type = 'month'
    format = '%d-%m-%Y'

class DateInput(forms.DateInput):
    input_type = 'date'
    format = '%d-%m-%Y'


class SearchAppointment(forms.Form):
    SEARCH_TYPE = (
        ('...', '...'),
        ('Name', 'Name'),
        ('Date', 'Date')
	)
    search_by = forms.ChoiceField(
         choices=SEARCH_TYPE
	)
    patient_name = forms.CharField(
         required=False,
		max_length=50,
		widget=forms.TextInput(attrs={
			'value': 'Insira nome',
			'placeholder': 'Nome de paciente',
			'oninvalid': "this.setCustomValidity('Por favor insira o seu nome de paciente')"
		}
	))
    date = forms.CharField(
		max_length=255,
        required=False,
		widget=DateInput
    )

class LoginForm(forms.Form):
	nome_do_usuario = forms.CharField(
		max_length=50,
		widget=forms.TextInput(attrs={
			'value': 'januario95',
			'placeholder': 'Nome de usuario',
			'oninvalid': "this.setCustomValidity('Por favor insira o seu nome de usuario')"
		}
	))
	palavra_passe = forms.CharField(
		max_length=50,
		widget=forms.PasswordInput(attrs={
			'value': 'Jaci1995',
			'placeholder': 'Palavra passe',
			'oninvalid': "this.setCustomValidity('Por favor insira a sua senha aqui')"
		}
	))


class AppointmentForm(forms.Form):
    first_name = forms.CharField(
		max_length=150,
        required=True,
		widget=forms.TextInput(attrs={
            'value': 'Reinata',
			'placeholder': 'Insira o seu primeiro nome',
			'oninvalid': "this.setCustomValidity('Por favor insira seu primeiro nome aqui')"
		}))
    last_name = forms.CharField(
		max_length=150,
        required=True,
		widget=forms.TextInput(attrs={
            'value': 'Cipriano',
			'placeholder': 'Insira o seu ultimo nome',
			'oninvalid': "this.setCustomValidity('Por favor insira seu ultimo nome aqui')"
		}))
    email = forms.CharField(
		max_length=150,
        required=False,
		widget=forms.EmailInput(attrs={
            'value': 'januario.cipriano@ayamed.co.mz',
			'placeholder': 'Insira o seu email',
			'oninvalid': "this.setCustomValidity('Por favor insira seu email aqui')"
		}))
    phone_number = forms.CharField(
		max_length=255,
        required=True,
		widget=forms.TextInput(attrs={
            'value': '865482431',
			'placeholder': 'Insira o seu numero de telefone',
			'oninvalid': "this.setCustomValidity('Por favor insira seu numero de telefone aqui')"
		}))
    disease = forms.CharField(
		max_length=255,
        required=True,
		widget=forms.TextInput(attrs={
            'value': 'Dor de cabeça',
			'placeholder': 'Insira o nome da doença',
			'oninvalid': "this.setCustomValidity('Por favor insira o nome da doença aqui')"
		}))
    # description = forms.CharField(
	# 	max_length=255,
    #     required=False,
	# 	widget=forms.Textarea(attrs={
    #         'text': 'Aquece me todo o corpo e fico sem apetite',
	# 		'placeholder': 'Insira a descriçao da doença',
	# 		'oninvalid': "this.setCustomValidity('Por favor insira a descriçao da doença aqui')"
	# 	}))
    date = forms.CharField(
		max_length=255,
        required=True,
		widget=DateInput
    )
    priority = forms.ChoiceField(
        choices=PRIORITY,
        required=False,  
        widget=forms.Select(attrs={'class': 'form-control'})
    )

app/templates/app/appointmets.html
{% extends "base.html" %}

{% block title %}
	<title>Marcar Consulta</title>
{% endblock %}

{% block style %}
	<style>
		.appointment-section {
			display: flex;
			width: 90%;
			flex-direction: column;
			justify-content: center;
			align-items: center;
		}
        .body-section {
            width: 80%;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            /*background-color: rgb(233, 246, 249); */
            padding: 15px;
            border-radius: 20px;
        }
        .body-section p {
            padding: 0px;
            margin: 0px;
        }
        .body-section form {
            width: 100%;
            padding: 6px 21px 21px 21px;
            max-width: 400px;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            /*border-radius: 40px;
            border: 1px solid #ccc;*/
        }
        .results-section {
            width: 100%;
            display: flex;
            align-items: center;
            justify-content: center;
        }
		select, input[type="submit"] {
            width: 100%;
            height: 31px;
        }
        select,
		input[type="text"],
        input[type="date"],
        input[type="month"],
        input[type="email"],
        input[type="submit"],
		#id_password {
            height: 28px;
            width: 100%;
            min-width: 160px;
            border-radius: 17px;
            border: 1px solid #ccc;
            text-align: center;
            outline: none;
        }
		input[type="submit"] {
			cursor: pointer;
		}
		select:focus,
		input[type="text"]:focus,
        input[type="date"]:focus,
        input[type="email"]:focus,
		input[type="submit"]:focus,
		#id_password:focus {
			
		}
		.result-section {
			width: 100%;
            min-width: 425px;
			padding: 20px;
			border-radius: 30px; /* 10px 10px 10px; */
			background-color: white;
			box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
		}
		.result-section table {
			width: 100%;
			border-collapse: collapse;
		}
		.result-section tr {
            font-size: 14px;
		}
        .tr-tbody {
            border-bottom: 1px solid #ccc;
        }
		.result-section th,
		.result-section td {
			/*border: 1px solid #ccc;*/
			padding: 5px;
		}
		.result-section td {
			font-size: 13px;
		}
		.row {
			display: flex;
			flex-direction: column;
			justify-content: center;
			align-items: center;
		}
		.gender {
			font-weight: normal;
		}
		.link {
			text-decoration: none;
		}
		td a {
			text-decoration: none;
		}

        .form-row {
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
        }
        .form-row label {
            font-size: 13px;
        }
        #id_priority {
            margin-bottom: 10px;
        }
        .asterisk {
            font-size: 10px;
            margin-top: 5px;
            color: white;
        }
        .center-td {
            text-align: center;
        }
        .patiente-field {
            display: none;
        }
        .date-field {
            display: none;
        }
        .submitted-fields {
            width: 100%;
            display: flex;
            align-items: center;
            justify-content: space-around;
        }
        .error {
            color: red;
            font-size: 11px;
            font-style: italic;
        }
        .highlight-row {
            color: white;
            background-color: goldenrod;
            transition: all 0.3s;
            font-size: 16px;
            transform: scale(1.05);
        }
        

		@media only screen and (max-width: 768px) {
            .body-section {
                
            }
			select, input[type="submit"] {
                width: 100%;
				max-width: 230px;
				height: 28px;
            }
			input[type="text"],
            input[type="date"],
            input[type="month"],
            input[type="email"],
			#id_password {
				width: 100%;
				height: 25px;
			}
            .form-row label {
                font-size: 12px;
            }
            .result-section tr {
                font-size: 12px;
            }
            .result-section td {
                font-size: 11px;
            }
		}
	</style>
{% endblock %}

{% block content %}
	<div class="appointment-section">
		<div class="body-section">
            <p>Pesquisar Consulta</p>
            <span class="error"></span>
			<form method="post">
                <div class="submitted-fields">
                    <div class="form-row">
                        <label for="id_search_by">Tipo de pesquisa</label>
                        <select name="search_by" id="id_search_by">
                            <option value="...">...</option>
                            <option value="Name">Name</option>
                            <option value="Date">Date</option>
                        </select>
                    </div>

                    <div class="form-row patiente-field">
                        <label for="id_patient_name">Nome do paciente</label>
                        {{ form.patient_name }}
                    </div>
                    <div class="form-row date-field">
                        <label for="id_date">Selecionar mes</label>
                        {{ form.date }}
                    </div>
                </div>
                
                {% csrf_token %}
                <div class="form-row">
                    <label for="">.</label>
                    <input type="submit" class="btn-submit" value="Pesquisar">
                </div>
            </form>
            <div class="result-section">
                <table>
                    <thead>
                        <tr>
                            <th class="table-header" style="border-top-left-radius:35px;border-bottom-left-radius:35px;">
                                #
                            </th>
                            <th class="table-header name" onclick="sortTable('name')">
                                Primeiro nome
                                <i class="fa-solid fa-sort"></i>
                            </th>
                            <th class="table-header amount" onclick="sortTable('amount')">
                                Ultimo nome
                                <i class="fa-solid fa-sort"></i>
                            </th>
                            <th class="table-header month" onclick="sortTable('month')">
                                Telefone
                                <i class="fa-solid fa-sort"></i>
                            </th>
                            <th class="table-header year" onclick="sortTable('year')">
                                Doença
                                <i class="fa-solid fa-sort"></i>
                            </th>
                            <th class="table-header type" onclick="sortTable('expense_type')">
                                Prioridade
                                <i class="fa-solid fa-sort"></i>
                            </th>
                            <th class="table-header priority" style="border-top-right-radius:35px;border-bottom-right-radius:35px;">
                                Terminada
                                <i class="fa-solid fa-sort"></i>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        
                    </tbody>
                </table>
            </div>
		</div>
	</div>
{% endblock %}

{% block javascript %}
	<script>
		let search_by = document.getElementById('id_search_by');
        let patienteField = document.querySelector('.patiente-field');
        let patientName = document.getElementById('id_patient_name');
        let dateField = document.querySelector('.date-field');
        let date = document.getElementById('id_date');
        date.value = getCurrentDate();

        let error = document.querySelector('.error');
        let btnSubmit = document.querySelector('.btn-submit');
        let tbody = document.querySelector('tbody');

        function getCurrentDate() {
            function formatDate(date) {
                if (parseInt(date) < 10) {
                    return '0' + date;
                }
                return date;
            }
            let today = new Date();
            return `${formatDate(today.getFullYear())}-${formatDate(today.getMonth()+1)}-${formatDate(today.getDate())}`;
        }

        search_by.addEventListener('change', e => {
            error.textContent = '';
            let value = e.target.value;
            if (value == 'Name') {
                dateField.style.display = 'none';
                patienteField.style.display = 'flex';
                date.value = getCurrentDate();
            } else if (value == 'Date') {
                patienteField.style.display = 'none';
                dateField.style.display = 'flex';
                // date.setAttribute('required', '');
                // patientName.removeAttribute('required');
                patientName.value = 'Insira nome';
            }
        });

        const arrayRange = (start, stop, step) =>
            Array.from(
                { length: (stop - start) / step + 1 },
                (value, index) => start + index * step
            );

        console.log();
        
        function highlightRow() {
            let range = arrayRange(1, 5, 1);
            let trs = document.querySelectorAll('.tr-tbody');
            for (let tr of trs) {
                //
            }
        }
        

            
        btnSubmit.addEventListener('click', e => {
            e.preventDefault();
            
            if (patientName.value === '') { // && date.value === getCurrentDate()) {
                // console.log(date.value)
                error.textContent = 'Preencha os campos!';
            } else {
                error.textContent = '';
                let csrfToken = "{{ csrf_token }}";
                fetch('/get_appointments_api/', {
                    method: 'POST',
                    headers: {
                        'Accept': 'application/json',
                        'Content-Type': 'application/json',
                        'X-CSRFToken': csrfToken
                    },
                    body: JSON.stringify({
                        'name': patientName.value,
                        'date': date.value
                    })
                })
                        .then(res => res.json())
                        .then(data => {
                            tbody.innerHTML = '';
                            // console.log(data);
                            let values = data.data;
                            if (values.length == 0) {
                                let tr = document.createElement('tr');
                                tr.innerHTML += `
                                    <td colspan="7" style="text-align:center;">No result for your filter.</td>
                                `;
                                tbody.appendChild(tr);
                            } else {
                                let index = 1;
                                for (let row of values) {
                                    let completed;
                                    if (row.completed) {
                                        completed = `<td class="center-td" style="color:#46ACC2;font-weight:bold;border-top-right-radius:35px;border-bottom-right-radius:35px;">✓</td>`
                                    } else {
                                        completed = `<td class="center-td" style="color:red;font-weight:bold;border-top-right-radius:35px;border-bottom-right-radius:35px;">✗</td>`;
                                    }
                                    let tr = document.createElement('tr');
                                    tr.classList.add('tr-tbody');
                                    tr.classList.add(`tr-${ index }`);
                                    tr.innerHTML += `
                                        <td style="text-align:center;border-top-left-radius:35px;border-bottom-left-radius:35px;">${ index }</td>
                                        <td class="center-td">${ row.patient.first_name }</td> 
                                        <td class="center-td">${ row.patient.last_name }</td>
                                        <td class="center-td">${ row.patient.phone_number }</td>
                                        <td class="center-td">${ row.disease }</td>
                                        <td class="center-td">${ row.priority }</td>
                                        ${ completed }
                                    `;
                                    tbody.appendChild(tr);
                                    let tr2 = $(`.tr-${ index }`);
                                    tr2.click(function() {
                                        console.log('Yes');
                                        tr2.toggleClass('highlight-row');
                                    });
                                    index += 1;
                                }
                                /*
                                let range = arrayRange(1, index, 1);
                                for (let id of range) {
                                    let tr = $(`.tr-${ id }`);
                                    tr.click(function() {
                                        console.log('Yes');
                                    });
                                }
                                */
                            }
                        })
                        .then(err => console.log(err));
            }
        });
	</script>
{% endblock %}

app/templates/app/login.html
{% extends "base.html" %}

{% block title %}
	<title>Marcar Consulta</title>
{% endblock %}

{% block style %}
	<style>
		.appointment-section {
			display: flex;
			width: 90%;
			flex-direction: column;
			justify-content: center;
			align-items: center;
			margin-top: 10px;
		}
        .body-section {
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            border: 1px solid #ccc;
            /*background-color: rgb(233, 246, 249); */
            background-color: #46ACC2;
            padding: 15px;
            border-radius: 20px;
        }
        .body-section p {
            padding: 0px;
            margin: 0px;
        }
		select, input[type="submit"] {
            width: 100%;
            height: 31px;
        }
        select,
		input[type="text"],
        input[type="password"],
        input[type="date"],
        input[type="email"],
        input[type="submit"],
		#id_password {
            height: 28px;
            width: 100%;
            min-width: 230px;
            border-radius: 17px;
            border: 1px solid #ccc;
            text-align: center;
            outline: none;
        }
		input[type="submit"] {
			cursor: pointer;
		}
		select:focus,
		input[type="text"]:focus,
        input[type="date"]:focus,
        input[type="email"]:focus,
		input[type="submit"]:focus,
		#id_password:focus {
			
		}
		.result-section {
			width: 100%;
			margin-top: 15px;
			border-top: 6px solid teal;
			padding: 20px;
			border-radius: 0px 0px 10px 10px;
			background-color: white;
			box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
		}
		.result-section table {
			width: 100%;
			border-collapse: collapse;
		}
		.result-section tr {
			border-bottom: 1px solid #ccc;
		}
		.result-section th,
		.result-section td {
			/*border: 1px solid #ccc;*/
			padding: 5px;
		}
		.result-section td {
			font-size: 13px;
		}
		.row {
			display: flex;
			flex-direction: column;
			justify-content: center;
			align-items: center;
		}
		.gender {
			font-weight: normal;
		}
		.link {
			text-decoration: none;
		}
		td a {
			text-decoration: none;
		}

        .form-row {
            display: flex;
            flex-direction: column;
            align-items: flex-start;
            justify-content: center;
            margin-top: 8px;
        }
        .form-row label {
            font-size: 13px;
            color: white;
        }
        #id_priority {
            margin-bottom: 10px;
        }
        .asterisk {
            font-size: 10px;
            margin-top: 5px;
            color: white;
        }
        .patient-exists {
            font-size: 11px;
            color: yellow;
            font-weight: bold;
        }
        

		@media only screen and (max-width: 768px) {
            .body-section {
                
            }
			select, input[type="submit"] {
                width: 100%;
				max-width: 230px;
				height: 28px;
            }
			input[type="text"],
            input[type="password"],
            input[type="date"],
            input[type="email"],
			#id_password {
				width: 100%;
				max-width: 230px;
				height: 25px;
			}
            .form-row label {
                font-size: 12px;
            }
		}
	</style>
{% endblock %}

{% block content %}
	<div class="appointment-section">
		<div class="body-section">
            <p>Marcar Consulta</p>
            {% if patient_exists %}
                <span class="patient-exists">A patient with these details already exists!</span>
            {% endif %}
			<form method="post">
                <div class="form-row">
                    <label for="id_nome_do_usuario">Nome do usuario<span class="required-field">*</span></label>
                    {{ form.nome_do_usuario }}
                </div>
                <div class="form-row">
                    <label for="id_palavra_passe">Palavra-passe<span class="required-field">*</span></label>
                    {{ form.palavra_passe }}
                </div>
                {% csrf_token %}
                <div class="form-row">
                    <input type="submit" class="btn-submit" value="Marcar">
                    <span class="asterisk">* Campos obrigatórios</span>
                </div>
            </form>
		</div>
	</div>
{% endblock %}

{% block javascript %}
	<script>
		
	</script>
{% endblock %}

app/templates/app/make_appointment.html
{% extends "base.html" %}

{% block title %}
	<title>Marcar Consulta</title>
{% endblock %}

{% block style %}
	<style>
		.appointment-section {
			display: flex;
			width: 90%;
			flex-direction: column;
			justify-content: center;
			align-items: center;
			margin-top: 10px;
		}
        .body-section {
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            border: 1px solid #ccc;
            /*background-color: rgb(233, 246, 249); */
            background-color: #46ACC2;
            padding: 15px;
            border-radius: 20px;
        }
        .body-section p {
            padding: 0px;
            margin: 0px;
        }
		select, input[type="submit"] {
            width: 100%;
            height: 31px;
        }
        select,
		input[type="text"],
        input[type="date"],
        input[type="email"],
        input[type="submit"],
		#id_password {
            height: 28px;
            width: 100%;
            min-width: 230px;
            border-radius: 17px;
            border: 1px solid #ccc;
            text-align: center;
            outline: none;
        }
		input[type="submit"] {
			cursor: pointer;
		}
		select:focus,
		input[type="text"]:focus,
        input[type="date"]:focus,
        input[type="email"]:focus,
		input[type="submit"]:focus,
		#id_password:focus {
			
		}
		.result-section {
			width: 100%;
			margin-top: 15px;
			border-top: 6px solid teal;
			padding: 20px;
			border-radius: 0px 0px 10px 10px;
			background-color: white;
			box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
		}
		.result-section table {
			width: 100%;
			border-collapse: collapse;
		}
		.result-section tr {
			border-bottom: 1px solid #ccc;
		}
		.result-section th,
		.result-section td {
			/*border: 1px solid #ccc;*/
			padding: 5px;
		}
		.result-section td {
			font-size: 13px;
		}
		.row {
			display: flex;
			flex-direction: column;
			justify-content: center;
			align-items: center;
		}
		.gender {
			font-weight: normal;
		}
		.link {
			text-decoration: none;
		}
		td a {
			text-decoration: none;
		}

        .form-row {
            display: flex;
            flex-direction: column;
            align-items: flex-start;
            justify-content: center;
            margin-top: 8px;
        }
        .form-row label {
            font-size: 13px;
            color: white;
        }
        #id_priority {
            margin-bottom: 10px;
        }
        .asterisk {
            font-size: 10px;
            margin-top: 5px;
            color: white;
        }
        .patient-exists {
            font-size: 11px;
            color: yellow;
            font-weight: bold;
        }
        

		@media only screen and (max-width: 768px) {
            .body-section {
                
            }
			select, input[type="submit"] {
                width: 100%;
				max-width: 230px;
				height: 28px;
            }
			input[type="text"],
            input[type="date"],
            input[type="email"],
			#id_password {
				width: 100%;
				max-width: 230px;
				height: 25px;
			}
            .form-row label {
                font-size: 12px;
            }
		}
	</style>
{% endblock %}

{% block content %}
	<div class="appointment-section">
		<div class="body-section">
            <p>Marcar Consulta</p>
			<form method="post">
                <div class="form-row">
                    <label for="id_first_name">Primeiro nome<span class="required-field">*</span></label>
                    {{ form.first_name }}
                </div>
                <div class="form-row">
                    <label for="id_last_name">Ultimo nome<span class="required-field">*</span></label>
                    {{ form.last_name }}
                </div>
                <div class="form-row">
                    <label for="id_email">Email</label>
                    {{ form.email }}
                </div>
                <div class="form-row">
                    <label for="id_desease">Doença<span class="required-field">*</span></label>
                    {{ form.disease }}
                </div>
                <div class="form-row">
                    <label for="id_phone_number">Numero de telefone<span class="required-field">*</span></label>
                    {{ form.phone_number }}
                </div>
                <div class="form-row">
                    <label for="id_date">Data</label>
                    {{ form.date }}
                </div>
                <div class="form-row">
                    <label for="id_priority">Prioridade</label>
                    {{ form.priority }}
                </div>
                {% csrf_token %}
                <div class="form-row">
                    <input type="submit" class="btn-submit" value="Marcar">
                    <span class="asterisk">* Campos obrigatórios</span>
                </div>
            </form>
		</div>
	</div>
{% endblock %}

{% block javascript %}
	<script>
		
	</script>
{% endblock %}

app/templates/app/navbar_view.html
{% load static %}
{% load format_words %}

<div class="Navbar">
    <div class="Navbar__Link Navbar__Link-brand">
        <a href="#">
            <img class="site-logo" src="{% static 'ayamed.jpg' %}">
        </a>
    </div>
    <div class="Navbar__Link Navbar__Link-toggle">
        <!-- <i class="fas fa-bars"></i> -->
        <span>≣</span>
    </div>
    <nav class="Navbar__Items">
        <div class="Navbar__Link">
            Ayamed
        </div>
    </nav>
    <nav class="Navbar__Items Navbar__Items--right">
        <div class="Navbar__Link">
            <a class="header-link estudantes" href="{% url 'app:marcacoes' %}">Marcacoes</a>
        </div>
        <div class="Navbar__Link">
            <a class="header-link professores" href="{% url 'app:make_appointment' %}">Professores</a>
        </div>
        <div class="Navbar__Link">
            <a class="header-link estatistica" href="{% url 'app:make_appointment' %}">Estatisticas</a>
        </div>
        {% if request.user.is_authenticated %}
            <div class="Navbar__Link">
                <a class="header-link perfil" href="{% url 'app:make_appointment' %}">
					Perfil - {{ request.user.first_name|get_first_letter }}{{ request.user.last_name|get_first_letter }}
				</a>
            </div>
            <div class="Navbar__Link">
                <a class="header-link" href="{% url 'app:logout' %}">Sair</a>
            </div>
        {% else %}
            <div class="Navbar__Link">
                <a class="header-link" href="{% url 'app:login' %}">Login</a>
            </div>
        {% endif %}
    </nav>
</div>


<script>
    function classToggle() {
        const navs = document.querySelectorAll('.Navbar__Items');
        navs.forEach(nav => nav.classList.toggle('Navbar__ToggleShow'));
    }
      
    document.querySelector('.Navbar__Link-toggle').addEventListener('click', classToggle);
</script>